NOSTORY: Fixed items usage error
boldlink/terraform-aws-dynamodb pull request #6
Opened 2022-06-03 10:49 UTC by patrickmukumbu

# Description

This PR has been created to fix the errors resulting from the usage of table items.

## Features/Fixes/Patches/Changes list:

Please check the [CHANGELOG.md](https://github.com/boldlink/terraform-aws-dynamodb/blob/fixes/ddb-item/CHANGELOG.md)

## Checklists:

### PR Owners Checklist:
* [ ] Have you followed the guidelines in our Contributing document?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [ ] Have you checked there aren't open [Pull Requests](../../../pulls) of upstream or parallel code that will cause conflicts?
* [ ] Have you updated the `CHANGELOG.md`?
* [ ] Have you updated the `README.md`(s)?
* [ ] OWNER: Does your submission pass?
    * [ ] Pre-commit (attach logs/print screen to this PR)
    * [ ] Checkov/terrascan (attach logs/print screen to this PR)
    * [ ] Terraform resources examples build/destroy successfully with Terraform 0.14.11 minimum?
* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?
* [ ] First PR? Have you deleted `## How to use this template...` from the root `.README.md`?

### PR Reviewers Checklists?
* [ ] Are all your comments/changes resolved?
* [ ] Are you happy with the OWNER checklists and additional information provided?
* [ ] Does your review tests pass?
    * [ ] Terraform resources examples build/destroy successfully with Terraform 0.14.11 minimum?

### Checkov Analysis Result
[dynamodb-checkov.txt](https://github.com/boldlink/terraform-aws-dynamodb/files/8831758/dynamodb-checkov.txt)

2022-06-07 11:32 UTC, hugoalmeida264 requested changes
Hi Patrick - see my comments

2022-06-07 11:32 UTC, hugoalmeida264 commented on CHANGELOG.md
> +### Added
No need to separate them on tho sections, we can have just one titles `Changes`

2022-06-07 11:32 UTC, hugoalmeida264 commented on examples/table_items/main.tf
> +    item = <<ITEM
Use `jsoncode()`

2022-06-07 21:40 UTC, patrickmukumbu commented
Corrected @hugoalmeida264 . Please have a look

2022-06-08 13:10 UTC, hugoalmeida264 approved these changes

2022-06-08 13:16 UTC, ndegwajohn approved these changes

2022-06-08 13:18 UTC, merged